### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by verilog15** [Hoogkamer/vue-org-chart#2]
Hello @Hoogkamer, 
I thought of using your project in mine. Before I decide to do so, I would like to some questions:

1. What do you mean by static web? Can I pass JSON data in run-time from the DB so it will build the chart?
2. Are there expose methods in order to click the node to open a modal?
3. What is the list of options I can use?
4. I would like to see a snippet of how using it (I saw the demo but not the code).
5. What is the status of the project? Is it safe to use it?
6. I tried to play a bit with the chart and I noticed that every time you expend some node, it takes noticeable time to return the lines which connect between the nodes. Are you thinking of fixing it?

**Comment by Hoogkamer** [comment]
Hi @verilog15, 

By a static website I mean that is works completely without a webserver, database or api calls.

This is not built as a library actually, but as a complete website. 
If you want to create your own website, you are better of using a library, like https://github.com/dabeng/OrgChart.js
So I do not expose any programmable parameters/methods.
Of course you could do all the things you wish, but than you have to change the source code.

The other questions:
5) yes it is safe to use, but no guarantees :)
6) I still need to find a way to solve it. Currently I use a timeout function of 0.5 seconds to draw the lines, because I need to wait with drawing the lines until everything is positioned.

Hope this helps,
Regards,
Michael

**Comment by Hoogkamer** [comment]
6) The drawing of lines is now improved so that they will be drawn without delay
